package com.demo.common.model;

import com.demo.common.model.base.BaseTTest;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TTest extends BaseTTest<TTest> {
	public static final TTest dao = new TTest().dao();
}
